[package]
name = "devils-fingers"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
edition = "2018"

[dependencies]
chrono = { version = "0.4", features = ["serde"] }
cidr = "0.1"
clap = "2"
ctrlc = { version = "3", features = ["termination"] }
etherparse = "0.9"
failure = { version = "0.1", default-features = false, features = ["std"] }
# so dumb, needed for a cast
generic-array = "0.14"
httparse = "1"
insideout = "0.2"
itertools = "0.9"
libc = "0.2"
log = "0.4"
nix = "0.18"
publicsuffix = { version = "1", default-features = false }
rand = "0.7"
septid = "0.1"
serde = "1"
serde_derive = "1"
serde_json = "1"
toml = "0.5"
zstd = "0.5"

[dev-dependencies]
hex = "0.4"

[profile.release]
lto = true
panic = "abort"
debug = true
