[package]
name = "pcap-http"
version = "0.1.0"
authors = ["Chris West (Faux) <git@goeswhere.com>"]
edition = "2018"

[dependencies]
etherparse = "0.9"
libc = "0.2"
zstd = "0.5"

[profile.release]
lto = true
